import React from "react";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        alignItems:'center',
        backgroundColor:'#353840',
    },
    uploadButton:{
        marginTop:'20%',
        backgroundColor:'#fff',
        width:165,
        height:165,
        borderRadius:90,
        justifyContent:'center',
        alignItems:'center',
        zIndex:5
    },
    uploadText:{
        zIndex:9,
        position:'absolute',
        fontSize:55,
        color:'#e52248',
        opacity:0.4
    },
    avatarImg:{
        width:160,
        height:160,
        borderRadius:80,
        opacity:0.9
    },
    nameText:{
        fontSize:28,
        color:'#fff',
        marginTop:20,
        marginHorizontal:20,
        fontWeight:'bold'
    },
    emailText:{
        fontSize:20,
        color:'#ddd',
        marginTop:9,
        marginHorizontal:20,
        fontStyle:'italic'
    },
    buttons:{
        width:'85%',
        marginTop:15,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#fff',
        height:45,
        borderRadius:5
    },
    buttonsTexts:{
        fontSize:20,
        color:'#000',
        fontWeight:'bold',
        marginLeft:5
    },
    modalContainer:{
        width:'100%',
        height:'50%',
        backgroundColor:'#fff',
        justifyContent:'center',
        alignItems:'center',
        position:'absolute',
        bottom:0
    },
    goBackButton:{
        position:'absolute',
        flexDirection:'row',
        top:15,
        left:25
    },
    input:{
        width:'85%',
        marginTop:15,
        padding:10,
        fontSize:20,
        textAlign:'center',
        backgroundColor:'#ddd',
        height:45,
        borderRadius:5
    }
})